config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" }
  devise_scope :user do
    get "/users/:id" => "users#show", as: "user_page"
    patch "/users/:id/edit" => "users#edit", as: "user_edit"
  end

  root "events#home"

  resources :events  
  get "/" => "events#home", as: "home"
  get "/search" => "events#search", as: "search"
  get "/search/results" => "events#results"
  post "/search/:city" => "events#location"


  get "/admin" => "songkick_artists#admin"
  get "/admin/songkick_artists/new" => "songkick_artists#new"
  post "/admin/songkick_artists" => "songkick_artists#create"
  get "/admin/songkick_artists" => "songkick_artists#index", as: "index"


  resources :posts
  get "/events/:id/posts/new" => "posts#new", as: "new_event_post"
  post "/events/:id/posts" => "posts#create", as: "event_posts"
  delete "/posts/:id" => "posts#destroy", as: "delete_post"
  


end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :user_name, presence: true
	# validates :picure, presence: true
	# validates :password, presence: true
	# validates :password, length: { in: 8..10 }
	validates :birthdate, presence: true
	validates :user_name, uniqueness: true
	validates :email, uniqueness: true
	# validates :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/

	


end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when omniauth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end


  # GET /resource/:id
    def show
      @user = User.find(params[:id])
    end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def new
		@user = User.new
		render 'new'
	end

	def create
		@user = User.new user_params
		if @user.save
			redirect_to(user_path(@user))
		else
			render 'new'
		end
	end

	def show
		@user = User.find(params[:id])
		@posts = Post.where(user_id: @user.id).order(created_at: :asc)
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])

		if @user.update(user_params)
			redirect_to(user_page_path(@user))
		else
			render edit_user_registration_path(@user)
		end
	end



	
	







	private
		def user_params
			params.require(:user).permit(:first_name, :last_name, :user_name, :email, :birthdate, :picture)
		end

end

app/views/users/edit.html.erb
<h2>Edit</h2>




<%= form_for( :user, url: user_edit_path(@user), method: :patch) do |f| %>



  <div class="field">
    <%= f.label :picture %><br>
    <%= f.file_field :picture %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :user_name %><br />
    <%= f.text_field :user_name %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>


  <div class="field">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
    <%= f.password_field :current_password, autocomplete: "off" %>
  </div>

  <div class="field">
    <%= f.label :birthdate %><br />
    <%= f.date_field :birthdate %>
  </div>

  <div class="actions">
    <%= f.submit "Update" %>
  </div>

<% end %>


<br><br>
<h3>Cancel my account</h3>





<%= link_to "Back", :back %>

app/views/users/new.html.erb
<h2>Log in</h2>

<%= form_for(resource, as: resource_name, url: session_path(resource_name)) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password, autocomplete: "off" %>
  </div>

  <% if devise_mapping.rememberable? -%>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end -%>

  <div class="actions">
    <%= f.submit "Log in" %>
  </div>
<% end %>

<%= render "devise/shared/links" %>

app/views/users/show.html.erb
<div class="container user">
	<%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link, edit-profile' %>
	<button><%= link_to('Create Event', new_event_path)%></button>
	<br><br>
	

	<h2>Hello <%= @user.first_name %>!</h2>

	<p class="user-info"><%= @user.picture %></p>
	<p class="user-info"><strong>Name:</strong> <%= @user.first_name %> <%= @user.last_name %></p>
	<p class="user-info"><strong>Email:</strong> <%= @user.email %></p>
	<p class="user-info"><strong>Birthdate:</strong> <%= @user.birthdate.strftime('%B %d %Y') %></p>
	<p class="user-info"><strong>About Me:<br></strong>I'm a web developer in south florida who loves music festivals, raves and general good times.</p>


	<div>
		<h3>Posts You've Made</h3>
		<ul class="comments">
			<% @posts.each do |post| %>
				<li><%= post.comments %></li>
			<% end %>
		</ul>
	</div>
</div>