config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" }
  devise_scope :user do
    get "/users/:id" => "users#show", as: "user_page"
    patch "/users/:id/edit" => "users#edit", as: "user_edit"
  end

  root "events#home"

  resources :events  
  get "/" => "events#home", as: "home"
  get "/search" => "events#search", as: "search"
  get "/search/results" => "events#results"
  post "/search/:city" => "events#location"


  get "/admin" => "songkick_artists#admin"
  get "/admin/songkick_artists/new" => "songkick_artists#new"
  post "/admin/songkick_artists" => "songkick_artists#create"
  get "/admin/songkick_artists" => "songkick_artists#index", as: "index"


  resources :posts
  get "/events/:id/posts/new" => "posts#new", as: "new_event_post"
  post "/events/:id/posts" => "posts#create", as: "event_posts"
  delete "/posts/:id" => "posts#destroy", as: "delete_post"
  


end

app/models/event.rb
class Event < ActiveRecord::Base
	require 'songkickr'
	has_and_belongs_to_many :artists
	has_many :posts


	validates :title, presence: true
	validates :title, format: {with: /\w/}
	validates :artist, presence: true
	validates :description, presence: true
	validates :date, presence: true
	validates :time, presence: true
	validates :venue, presence: true
	validates :venue, format: {with: /\w/}
	validates :city, presence: true
	validates :city, format: {with: /\w/}
	validates :ticket, presence: true
	

	def self.search(title, artist, date, city, venue)
		query = self
		query = query.where('title ILIKE :title', title: "%#{title}%") if title.present?
		query = query.where('artist ILIKE :artist', artist: "%#{artist}%") if artist.present?
		query = query.where(date: "#{date}") if date.present?
		query = query.where('city ILIKE :city', city: "%#{city}%") if city.present?
		query = query.where('venue ILIKE :venue', venue: "%#{venue}%") if venue.present?
		return query
	end


	def self.event_exists(title, date)
		if Event.exists?(['title ILIKE :title', title: "%#{title}%"]) && Event.exists?(date: date)
			return "yes"
		else
			return "no"
		end
	end

	def self.location_events(city)
		date = Time.now
		where('city ILIKE :city', city: "%#{city}%").where(date: (Time.now.midnight..date.days_since(30))).order(date: :asc)
		# binding.pry
	end


end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	def home
	end

	def results
		@title = params[:title]
		@artist = params[:artist]
		@date = params[:date]
		@city = params[:city]
		@venue = params[:venue]
		@search = Event.search(@title, @artist, @date, @city, @venue)
		
		if @search.empty?
			flash[:nothing] = "Sorry, nothing in the database matched your search fields."
			render 'home'
		else
			@results = @search.order(date: :asc)
			render 'results'
		end
	end

	def new
		@event = Event.new
		render 'new'
	end

	def create
		@event = Event.new event_params
		title = @event.title
		date = @event.date
		@exist = Event.event_exists(title, date)
		
		if @exist == "yes" 
			flash[:found] = "Event already exist in database."
			redirect_to(new_event_path)
		else
			if @event.save
				flash[:notice] = "Event created succesfully"
				redirect_to(event_path(@event))
			else
				flash[:alert] = "Event not created"
				render 'new'
			end
		end
	end

	def show
		@event = Event.find(params[:id])
		@posts = Post.where(event_id: "#{@event.id}")
	end

	def location
		@city = params[:city]
		@events = Event.all
		@location_month_events = @events.location_events(@city)
		# @location_month_events.where(date: (date.beginning_of_day..date.end_of_day))
		render json: @location_month_events
	end

	def edit
		@event = Event.find(params[:id])
	end

	def update
		@event = Event.find(params[:id])
		if @event.update_attributes(event_params)
			flash[:notice] = "Event updated succesfully"
			redirect_to action: 'show', controller: 'events', id: @event.id
		else
			flash[:alert] = "Event not updated"
			render 'edit'
		end
	end







	private
		def event_params
			params.require(:event).permit(:title, :description, :date, :artist, :time, :venue, :city, :ticket)
		end

end

app/views/events/edit.html.erb
<h2>EDIT EVENT</h2>


<nav class="navbar-sub">
	<%= link_to('Cancel', event_path(@event.id)) %>
</nav>


<%= render "shared/eventform" %>

app/views/events/home.html.erb
<div class="home">

	<div class="row bckgrd-img">
		<div class="row-search">
			
			<div class="col-sm-12 search-form clearfix">
				<h2 class="search-title">All Your Favorite Acts In One Place</h2>
				<div class="flash-msg">
					<% if flash[:nothing] %>
						<%= flash[:nothing] %>
					<% end %>
				</div>
				<%= form_tag("/search/results", method: "get") do %>
					<!--<div class="form-tag">
					  <%= label_tag(:event, "Event") %><br>
					  <%= search_field_tag(:event) %>
					</div>-->
					<div class="form-tag">
					  <%= label_tag(:artist, "Artists") %><br>
					  <%= search_field_tag(:artist) %>
					  <p class="label-text">Separate by commas</p>
					</div>

					<div class="form-tag">
					  <%= label_tag(:date, "Date") %><br>
					  <%= date_field_tag(:date) %>
					</div>

					<div class="form-tag">
					  <%= label_tag(:city, "City") %><br>
					  <%= search_field_tag(:city) %>
					</div>

					<div class="form-tag">
					  <%= label_tag(:venue, "Venue") %><br>
					  <%= search_field_tag(:venue) %>
					</div>

					<div class="form-btns">
					  <%= submit_tag("Search", :class => "btn-default btn") %>
					  <%= button_to("Reset", home_path, :class => "btn-default btn") %>
					</div>
				<% end %>
			</div>
		</div>

	</div>

	<div class="row">
		<div class="col-sm-6">
			<h3>Today's Events</h3>
			<ul class="js-today today">
				<p>No events for today.</p>
			</ul>
		</div>

		<div class="col-sm-6">
			<h3>What's Coming Up</h3>
			<ul class="js-30days month">
				<p>No events for the next 30 days.</p>
			</ul>
		</div>
	</div>







</div>

app/views/events/index.html.erb
<h1>THIS IS THE INDEX PAGE</h1>


<button>
	<%= link_to('Create Event', new_event_path) %>
</button>

app/views/events/new.html.erb
<h2>Create Event</h2>


<%= render "shared/eventform" %>

app/views/events/no.html.erb
<h2>NOTHING FOUND</h2>

app/views/events/results.html.erb
<h1>SEARCH RESULTS</h1>

<ul>
	
	<% @results.each do |event|%>
		<li>
			<% @title =  event.title %>
			<%= link_to("#{@title}", event_path(event.id)) %> @ <%= event.date %><br>
		</li>
	<% end %>
</ul>

app/views/events/show.html.erb
<!-- <nav class="navbar-sub">
	<%= link_to('Edit', edit_event_path(@event)) %>
</nav> -->


<div class="row event-img">
	
</div>

<div class="col-sm-6 posts-container">

	<h2>COMMENTS</h2>
	<p class="post-title">
	<%= link_to("Write A Post", new_event_post_path)%><span class="fa fa-pencil"></span></p>
	<ul class="comments">
		<% @posts.each do |post| %>
			<div class="comment-box clearfix">
				<li>
					<div class="user-img"></div>
					<div class="user-text">
						<p><span class="user-name">
							<% num = post.user_id %>
							<% user = User.find(num) %>
							<%= user.user_name %>
						</span><br>
						<%= post.comments %>
						<% if user_signed_in? %>
							<% if post.user_id == current_user.id %>
								<%= link_to('Delete', delete_post_path(post.id), :method => :delete) %>
							<% end %>
						<% end %></p>
					</div>
				</li>
			</div>
		<% end %>
	</ul>

</div>


<div class="col-sm-6 event-info-container">
	<h3><%= @event.title %></h3>
	<p><span class="fa fa-music"></span><%= @event.artist %></p>
	<p><span class="fa fa-pencil"></span><%= @event.description %></p>
	<p><span class="fa fa-calendar"></span><%= @event.date.strftime('%a %b %d, %Y') %></p>
	<p><span class="fa fa-clock-o"></span><%= @event.time.strftime('%I:%M %p') %></p>
	<p><span class="fa fa-building"></span><%= @event.venue %></p>
	<p><span class="fa fa-plane"></span><%= @event.city %></p>
	<p><span class="fa fa-ticket"></span>Purchase Tickets Here: <a href=<%= @event.ticket %> target="_blank"><%=@event.ticket%></a></p>
</div>