config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" }
  devise_scope :user do
    get "/users/:id" => "users#show", as: "user_page"
    patch "/users/:id/edit" => "users#edit", as: "user_edit"
  end

  root "events#home"

  resources :events  
  get "/" => "events#home", as: "home"
  get "/search" => "events#search", as: "search"
  get "/search/results" => "events#results"
  post "/search/:city" => "events#location"


  get "/admin" => "songkick_artists#admin"
  get "/admin/songkick_artists/new" => "songkick_artists#new"
  post "/admin/songkick_artists" => "songkick_artists#create"
  get "/admin/songkick_artists" => "songkick_artists#index", as: "index"


  resources :posts
  get "/events/:id/posts/new" => "posts#new", as: "new_event_post"
  post "/events/:id/posts" => "posts#create", as: "event_posts"
  delete "/posts/:id" => "posts#destroy", as: "delete_post"
  


end

app/models/songkick_artist.rb
class SongkickArtist < ActiveRecord::Base
	require 'songkickr'
	attr_accessor :exist, :added


	def self.find_artists(songkick_events)
		@exist = []
		@added = []
		
		songkick_events.each do |event|
			#event title
				if event.display_name == nil
					@title = "Unknown"
				else
					@title = event.display_name
				end

			#artist
				@performers = event.performances.map do |artist|
					artist.display_name
				end
				@artist = @performers.join(", ")

			#date & time
				if event.start == nil
					@date = "Unknown"
				else
					@date = event.start
				end

			#web link
				if event.uri == nil
					@link = "http://www.songkick.com/search?utf8=%E2%9C%93&type=initial&query=" + event.display_name
				else
					@link = event.uri
				end

			#venue
				if event.venue.display_name == nil
					@venue = "Unknown"
				else
					@venue = event.venue.display_name
				end

			#location
				if event.location.city == nil
					@city = "Unknown"
				else
					@city = event.location.city
				end

			#description
				if event.venue.description == nil
					@text = "An awesome " +event.type+ "."
				else
					@text = event.venue.description
				end

			create_event(@title, @artist, @text, @date, @venue, @city, @link)
		end
	end

	def self.create_event(title, artist, text, date, venue, city, link)
		if Event.exists?(['title ILIKE :title', title: "%#{title}%"]) && Event.exists?(date: date)
			@exist.push(title)
		else
			Event.create(title: (@title), artist: (@artist), description: (@text), date: (@date), time: (@date), venue: (@venue), city: (@city), ticket: (@link))
			@added.push(@title)
		end	
	end

	def self.record_found
		@exist		
	end

	def self.events_added
		@added
	end


end

app/controllers/songkick_artists_controller.rb
class SongkickArtistsController < ApplicationController


	def admin
		render 'home'
	end

	def new
		render 'new'
	end

	def create
		artist = params[:artist]
		remote = Songkickr::Remote.new Rails.configuration.x.songkick.api_key
		results_object = remote.events(:artist_name => artist)
		songkick_events = results_object.results
		
		new_artist = SongkickArtist.all
		new_artist.find_artists(songkick_events)
		@exist = new_artist.record_found
		@results = new_artist.events_added

		render 'index'
	end

	# def index
		
	# end






	private
		def artist_params
			params.require(:songkick_artist).permit(:artist)
		end


end

app/views/songkick_artists/home.html.erb
<div class="container admin-page">

	<h1>HELLO ADMIN!</h1>



	<%= button_to("Add New Artist to Database", admin_songkick_artists_new_path, :class => "btn-default btn") %>


</div>

app/views/songkick_artists/index.html.erb
<div class="container admin-page">

	<div class="col-sm-6">
		<H3>EVENTS ADDED</H3>
		<ul>
			<% @results.each do |event| %>
				<li><%= event %></li>
			<% end %>
		</ul>
	</div>
	

	<div class="col-sm-6">
		<H3>EVENTS ALREADY EXIST</H3>
		<ul>
			<% @exist.each do |event| %>
				<li><%= event %></li>
			<% end %>
		</ul>
	</div>
	


</div>

app/views/songkick_artists/new.html.erb
<div class="container admin-page">
	<h1>ADMIN LOGGED IN</h1>



	<%= form_tag ("/admin/songkick_artists"), :method => :post do %>
		<%= label_tag(:artist, "Artist(s):") %>
		<%= text_field_tag(:artist) %>

		<%= submit_tag("Add", :class => "btn-default btn") %>
	<% end %>


</div>