config/routes.rb
Rails.application.routes.draw do

  # devise_for :users
  devise_for :users, controllers: { sessions: "users/sessions" }
  devise_scope :user do
    get "/users/:id" => "users#show", as: "user_page"
    patch "/users/:id/edit" => "users#edit", as: "user_edit"
  end

  root "events#home"

  resources :events  
  get "/" => "events#home", as: "home"
  get "/search" => "events#search", as: "search"
  get "/search/results" => "events#results"
  post "/search/:city" => "events#location"


  get "/admin" => "songkick_artists#admin"
  get "/admin/songkick_artists/new" => "songkick_artists#new"
  post "/admin/songkick_artists" => "songkick_artists#create"
  get "/admin/songkick_artists" => "songkick_artists#index", as: "index"


  resources :posts
  get "/events/:id/posts/new" => "posts#new", as: "new_event_post"
  post "/events/:id/posts" => "posts#create", as: "event_posts"
  delete "/posts/:id" => "posts#destroy", as: "delete_post"
  


end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElectricShow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href="//fonts.googleapis.com/css?family=Codystar" rel="stylesheet" type="text/css">
  <%= csrf_meta_tags %>
</head>
<body class="">


<div class="container-fluid">



	<header class="clearfix">
		<nav class="navbar-bar navbar-fixed-top">
			<h1 class="navbar-text pull-left title-logo">
			 	<%= link_to 'PLURvents', home_path, :class => 'navbar-link' %>
			</h1>

			<% if user_signed_in? %>
				<p class="navbar-text pull-right navbar-links">
					<%= link_to 'Hello ' +current_user.user_name+ '!', user_page_path(current_user.id), :class => 'hello-user' %>
					<%= link_to 'View Profile', user_page_path(current_user.id) %>
					<%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'%>
				</p>
			<% else %>
				<p class="navbar-text pull-right navbar-links">
					<%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %>
					<%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
				</p>
			<% end %>
		</nav>
	</header>



		<% if notice %>
		  <p class="alert alert-success"><%= notice %></p>
		<% end %>
		<% if alert %>
		  <p class="alert alert-danger"><%= alert %></p>
		<% end %>
	<main>
	
		<%= yield %>
	</main>


	<footer class="row footer-container">
		<div class="col-sm-12 footer"></div>
	</footer>


</div>



<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<%= javascript_include_tag 'application' %>
</body>
</html>